using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CasualtiesMiner.Generators;

#pragma warning disable RS1035 // explicit Environment.NewLine usage; deliberate for readability

[Generator]
public sealed class ModelGenerator : IIncrementalGenerator
{
    public static readonly List<string> Models =
        [
            "ItemInfo",
            "BlockInfo",
            "RecipeItem",
            "LiquidType"
        ];

    //private const string AttributeSource = """
    //    // <auto-generated/>
    //    #nullable enable
    //    using System;
    //
    //    namespace xrmpe_launcher.Models;
    //
    //    /// <summary>
    //    /// Marks a partial class as the target for <c>ViewLocatorGenerator</c>:
    //    /// a <c>Build(object? data)</c> method will be generated that maps every
    //    /// <c>XxxViewModel</c> in the compilation to its <c>XxxView</c> sibling.
    //    /// </summary>
    //    internal sealed class ViewLocatorAttribute : Attribute { }
    //    """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Uncomment this line to debug the generator
#if DEBUG
        if (!System.Diagnostics.Debugger.IsAttached)
        {
            System.Diagnostics.Debugger.Launch();
        }
#endif

        //context.RegisterPostInitializationOutput(ctx =>
        //    ctx.AddSource("Models.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));
        // foreach (var reference in context.CompilationProvider.References)
        // {
        //     var assembly = context.CompilationProvider.GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;
        // }
        // 
        // var candidates = context.SyntaxProvider
        //     .CreateSyntaxProvider(
        //         static (node, _) => node is ClassDeclarationSyntax,
        //         static (ctx, _) => (INamedTypeSymbol?)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node))
        //     .Where(x => x is not null)
        //     .Collect();
        // 
        // var compilationAndLocators = context.CompilationProvider.Combine(candidates);

        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
        {
            foreach (var reference in compilation.References)
            {
                var asm = compilation
                    .GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;

                if (asm is null)
                    continue;

                if (asm.Name is "Assembly-CSharp")
                {
                    VisitNamespace(asm.GlobalNamespace);
                }

                var pairs = FindModelClasses(compilation);

                foreach (var locator in locatorTypes)
                {
                    var code = GenerateLocator(locator, pairs);
                    spc.AddSource($"{locator.Name}.g.cs", SourceText.From(code, Encoding.UTF8));
                }
            }
        });
    }

    private static ImmutableArray<(INamedTypeSymbol Vm, IEnumerable<IFieldSymbol> Fields)> FindModelClasses(Compilation compilation)
    {
        var allTypes = new List<INamedTypeSymbol>();
        CollectTypes(compilation.Assembly.GlobalNamespace, allTypes);

        var typesBySimpleName = allTypes.ToLookup(t => t.Name);

        var builder = ImmutableArray.CreateBuilder<(INamedTypeSymbol, IEnumerable<IFieldSymbol>)>();
        foreach (var type in allTypes)
        {
            if (type.TypeKind != TypeKind.Class || type.IsAbstract)
            {
                continue;
            }

            var fields = GetFields(type);

            builder.Add((type, fields));
        }

        return builder.ToImmutable();
    }

    private static void CollectTypes(INamespaceSymbol ns, List<INamedTypeSymbol> sink)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol child:
                    CollectTypes(child, sink);
                    break;
                case INamedTypeSymbol type:
                    sink.Add(type);
                    break;
            }
        }
    }

    private static IEnumerable<IPropertySymbol> GetProperties(INamedTypeSymbol type)
    {
        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);
    }

    private static IEnumerable<IFieldSymbol> GetFields(INamedTypeSymbol type)
    {
        return type.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic);
    }

    private static void VisitNamespace(INamespaceSymbol ns)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                VisitNamespace(childNs);
            }
            else if (member is INamedTypeSymbol type)
            {
                if (!Models.Any(type.Name.Contains))
                {
                    continue;
                }

                VisitType(type);
            }
        }
    }

    private static void VisitType(INamedTypeSymbol type)
    {
        if (IsMonoBehaviour(type))
        {
            var name = type.ToDisplayString();

            if (!Models.Any(type.Name.Contains))
            {
                return;
            }


        }

        foreach (var nested in type.GetTypeMembers())
        {
            VisitType(nested);
        }
    }

    private static bool IsMonoBehaviour(INamedTypeSymbol type)
    {
        var current = type;

        while (current != null)
        {
            if (current.ToDisplayString() == "UnityEngine.MonoBehaviour")
                return true;

            current = current.BaseType;
        }

        return false;
    }

    private static string GenerateLocator(INamedTypeSymbol locator, ImmutableArray<(INamedTypeSymbol Vm, IEnumerable<IFieldSymbol> View)> pairs)
    {
        var ns = "CasualtiesMiner.Shared.Models";
        //locator.ContainingNamespace.IsGlobalNamespace
        //? null
        //: locator.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(locator.Name);
        sb.AppendLine("{");

        //foreach (var (vm, view) in pairs)
        //{
        //    sb.Append("            ")
        //      .Append(vm.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
        //      .Append(" vm => new ")
        //      .Append(view.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
        //      .AppendLine(" { DataContext = vm },");
        //}

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

