<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <Import Project="../CasualtiesMiner.Common.props" />

    <ItemGroup>
        <PackageReference Include="ICSharpCode.Decompiler" Version="10.0.1.8346" />
        <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    </ItemGroup>
</Project>