<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <Import Project="../CasualtiesMiner.Common.props"/>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <PublishAot>true</PublishAot>
        <TrimMode>partial</TrimMode>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CasualtiesMiner.Dumper\CasualtiesMiner.Dumper.csproj"/>
    </ItemGroup>

    <!-- Copy ze files -->
    <ItemGroup>
        <None Include="..\libs\Assembly-CSharp.dll" CopyToOutputDirectory="PreserveNewest"
              Condition="Exists('..\libs\Assembly-CSharp.dll')"/>
    </ItemGroup>
</Project>