<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="10.0.1.8346" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\libs\Assembly-CSharp.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\libs\Assembly-CSharp.dll')" />
  </ItemGroup>

</Project>
