using System.Text;
using CasualtiesMiner.Shared.Models;

namespace CasualtiesMiner.Uploader.Wiki;

internal static partial class WikiGenerator
{
    private const string GeneratedHeader =
        "-- AUTO-GENERATED by CasualtiesMiner.Uploader. Do not edit by hand.";
    
    private static string BuildTableDataModule<TRow>(
        IEnumerable<TRow> rows,
        Func<TRow, IEnumerable<(string Key, string Value)> > rowMapper)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var row in rows)
        {
            sb.AppendLine("  {");

            foreach (var (key, value) in rowMapper(row))
            {
                sb.Append("    ").Append(key).Append(" = ").Append(value).AppendLine(",");
            }

            sb.AppendLine("  },");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string LuaList(IReadOnlyList<string> values)
    {
        if (values.Count == 0)
        {
            return "{}";
        }

        return "{ " + string.Join(", ", values.Select(LuaFormat.String)) + " }";
    }

    public static string ToHex(this Color c) =>
        c.a == 255
            ? $"#{c.r:x2}{c.g:x2}{c.b:x2}"
            : $"#{c.r:x2}{c.g:x2}{c.b:x2}{c.a:x2}";
}
