name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
