using CasualtiesMiner.Uploader.Data;
using CasualtiesMiner.Uploader.Data.Locale;
using System.Text;

namespace CasualtiesMiner.Uploader.Wiki;

/// <summary>
/// Generates <c>Module:Locale/&lt;lang&gt;/items</c> and <c>.../ui</c> from game locale JSON files.
/// </summary>
internal static class LocaleWikiGenerator
{
    private const string GeneratedHeader =
        "-- AUTO-GENERATED by CasualtiesMiner.Uploader. Do not edit by hand.";

    /// <summary>
    /// Game <c>other</c> keys copied into every locale's UI module (with English fallbacks).
    /// </summary>
    private static readonly (string Key, string GameKey, string Fallback)[] UiKeys =
    [
        ("lbl_internal_id", "internal_id", "Internal id"),
        ("lbl_category", "category", "Category"),
        ("lbl_weight", "weight", "Weight"),
        ("lbl_value", "itemvalue", "Trade value"),
        ("lbl_tags", "tags", "Tags"),
        ("lbl_qualities", "itemqualities", "Qualities"),
        ("section_description", "description", "Description"),
    ];

    private static readonly (string CategoryId, string Fallback)[] CategoryLabels =
    [
        ("medical", "Medical"),
        ("drug", "Drugs"),
        ("food", "Food"),
        ("water", "Drinks"),
        ("tool", "Tools"),
        ("utility", "Utility"),
        ("container", "Containers"),
        ("trash", "Trash"),
        ("custom", "Miscellaneous"),
        ("unobtainable", "Unobtainable"),
    ];

    public static string ModuleTitle(string langCode, string suffix)
    {
        return $"Module:Locale/{langCode}/{suffix}";
    }

    public static string BuildObjectsLocaleModule(GameLocale locale, IReadOnlyCollection<string> objectIds, string type)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var id in objectIds.OrderBy(x => x, StringComparer.Ordinal))
        {
            string name = string.Empty;
            string description = string.Empty;

            if (type == "main")
            {
                name = locale.GetObjectName(id);
                description = locale.GetObjectDescription(id);
            }
            if (type == "other")
            {
                name = locale.GetOther(id, $"{id}:TEMP_SMTH_IS_WRONG");
                description = locale.GetOtherDesc(id, $"{id}:TEMP_SMTH_IS_WRONG");
            }
            if (type == "moodles")
            {
                name = locale.GetMoodles(id, $"{id}:TEMP_SMTH_IS_WRONG");
                description = locale.GetMoodlesDesc(id, $"{id}:TEMP_SMTH_IS_WRONG");
            }

            sb.Append("  [").Append(LuaFormat.String(id)).Append("] = { ");
            sb.Append("name = ").Append(LuaFormat.String(name)).Append(", ");
            sb.Append("description = ").Append(LuaFormat.String(description));
            sb.AppendLine(" },");

        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // TODO: Fix this IReadOnlyList<LiquidRow> later because now we have
    // discrepancy between BuildLiquidsLocaleModule and BuildObjectsLocaleModule
    public static string BuildLiquidsLocaleModule(GameLocale locale, IReadOnlyList<LiquidRow> liquids)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var liquid in liquids.OrderBy(l => l.LiquidId, StringComparer.Ordinal))
        {
            var localeKey = liquid.LocaleName;
            var name = locale.GetOther(localeKey, $"{liquid.LiquidId}:TEMP_SMTH_IS_WRONG");
            var description = locale.GetOtherDesc(localeKey, $"{liquid.LiquidId}:TEMP_SMTH_IS_WRONG");

            sb.Append("  [").Append(LuaFormat.String(liquid.LiquidId)).Append("] = { ");
            sb.Append("name = ").Append(LuaFormat.String(name)).Append(", ");
            sb.Append("description = ").Append(LuaFormat.String(description));
            sb.AppendLine(" },");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string BuildUiModule(GameLocale locale)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        //UI keys
        foreach (var (key, gameKey, fallback) in UiKeys)
        {
            var value = locale.GetOther(gameKey, fallback);
            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        //Item categories
        foreach (var (categoryId, fallback) in CategoryLabels)
        {
            var key = "cat_" + categoryId;

            // Game locale has no dedicated category names; use English defaults until translators add keys.
            var value = locale.GetOther(key, fallback);
            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        //cq categories
        foreach (var (key, value) in locale.Other.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            if (key.Length <= 2
                || !key.StartsWith("cq", StringComparison.OrdinalIgnoreCase)
                || key.EndsWith("dsc", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string BuildWikiUiModule()
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("-- Wiki-only labels (body fields, moodle cause strings). Not from game locale files.");
        sb.AppendLine("return {");

        foreach (var (path, label) in WikiUiLabels.BodyFields.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.Append("  [")
              .Append(LuaFormat.String(path))
              .Append("] = ")
              .Append(LuaFormat.String(label))
              .AppendLine(",");
        }

        foreach (var (key, label) in WikiUiLabels.Misc.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.Append("  [")
              .Append(LuaFormat.String(key))
              .Append("] = ")
              .Append(LuaFormat.String(label))
              .AppendLine(",");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
