using CasualtiesMiner.Uploader.Data;
using CasualtiesMiner.Uploader.Data.Enums;
using CasualtiesMiner.Uploader.Data.Locale;
using System.Text;

namespace CasualtiesMiner.Uploader.Wiki;

/// <summary>
/// Generates <c>Module:Locale/&lt;lang&gt;/items</c> and <c>.../ui</c> from game locale JSON files.
/// </summary>
internal static class LocaleWikiGenerator
{
    private const string GeneratedHeader =
        "-- AUTO-GENERATED by CasualtiesMiner.Uploader. Do not edit by hand.";

    /// <summary>
    /// Game <c>other</c> keys copied into every locale's UI module (with English fallbacks).
    /// </summary>
    private static readonly (string Key, string GameKey, string Fallback)[] UiKeys =
    [
        ("lbl_internal_id", "internal_id", "Internal id"),
        ("lbl_category", "category", "Category"),
        ("lbl_weight", "weight", "Weight"),
        ("lbl_value", "itemvalue", "Trade value"),
        ("lbl_tags", "tags", "Tags"),
        ("lbl_qualities", "itemqualities", "Qualities"),
        ("section_description", "description", "Description"),
    ];

    private static readonly (string CategoryId, string Fallback)[] CategoryLabels =
    [
        ("medical", "Medical"),
        ("drug", "Drugs"),
        ("food", "Food"),
        ("water", "Drinks"),
        ("tool", "Tools"),
        ("utility", "Utility"),
        ("container", "Containers"),
        ("trash", "Trash"),
        ("custom", "Miscellaneous"),
        ("unobtainable", "Unobtainable"),
    ];

    public static string ModuleTitle(string langCode, string suffix)
    {
        return $"Module:Locale/{langCode}/{suffix}";
    }

    public static string BuildLocaleModule(GameLocale locale, IEnumerable<LocaleModuleEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var entry in entries.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            var (name, description) = ResolveLocaleStrings(locale, entry);

            sb.Append("  [").Append(LuaFormat.String(entry.Key)).Append("] = { ");
            sb.Append("name = ").Append(LuaFormat.String(name)).Append(", ");
            sb.Append("description = ").Append(LuaFormat.String(description));
            sb.AppendLine(" },");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static (string Name, string Description) ResolveLocaleStrings(GameLocale locale, LocaleModuleEntry entry)
    {
        var fallback = $"{entry.Key}:TEMP_SMTH_IS_WRONG";

        return entry.Type switch
        {
            GameObjectType.Item => (
                locale.GetObjectName(entry.LocaleKey),
                locale.GetObjectDescription(entry.LocaleKey)),
            GameObjectType.Block => (
                locale.GetOther(entry.LocaleKey, fallback),
                string.Empty),
            GameObjectType.Moodle => (
                locale.GetMoodles(entry.LocaleKey, fallback),
                locale.GetMoodlesDesc(entry.LocaleKey, fallback)),
            GameObjectType.Liquid => (
                locale.GetOther(entry.LocaleKey, fallback),
                locale.GetOtherDesc(entry.LocaleKey, fallback)),
            GameObjectType.Building => (
                locale.GetBuildings(entry.LocaleKey, fallback),
                locale.GetBuildingsDesc(entry.LocaleKey, fallback)),
            _ => (fallback, fallback),
        };
    }

    public static string BuildUiModule(GameLocale locale)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var (key, gameKey, fallback) in UiKeys)
        {
            var value = locale.GetOther(gameKey, fallback);
            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        foreach (var (categoryId, fallback) in CategoryLabels)
        {
            var key = "cat_" + categoryId;
            var value = locale.GetOther(key, fallback);
            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        foreach (var (key, value) in locale.Other.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            if (key.Length <= 2
                || !key.StartsWith("cq", StringComparison.OrdinalIgnoreCase)
                || key.EndsWith("dsc", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string BuildWikiUiModule()
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("-- Wiki-only labels (body fields, moodle cause strings). Not from game locale files.");
        sb.AppendLine("return {");

        foreach (var (path, label) in WikiUiLabels.BodyFields.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.Append("  [")
              .Append(LuaFormat.String(path))
              .Append("] = ")
              .Append(LuaFormat.String(label))
              .AppendLine(",");
        }

        foreach (var (key, label) in WikiUiLabels.Misc.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.Append("  [")
              .Append(LuaFormat.String(key))
              .Append("] = ")
              .Append(LuaFormat.String(label))
              .AppendLine(",");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
