using System.Text;
using CasualtiesMiner.Uploader.Data;

namespace CasualtiesMiner.Uploader.Wiki;

/// <summary>
/// Generates <c>Module:Locale/&lt;lang&gt;/items</c> and <c>.../ui</c> from game locale JSON files.
/// </summary>
public static class LocaleWikiGenerator
{
    private const string GeneratedHeader =
        "-- AUTO-GENERATED by CasualtiesMiner.Uploader. Do not edit by hand.";

    /// <summary>
    /// Game <c>other</c> keys copied into every locale's UI module (with English fallbacks).
    /// </summary>
    private static readonly (string Key, string GameKey, string Fallback)[] UiKeys =
    [
        ("lbl_internal_id", "internal_id", "Internal id"),
        ("lbl_category", "category", "Category"),
        ("lbl_weight", "weight", "Weight"),
        ("lbl_value", "itemvalue", "Trade value"),
        ("lbl_tags", "tags", "Tags"),
        ("lbl_qualities", "itemqualities", "Qualities"),
        ("section_description", "description", "Description"),
    ];

    private static readonly (string CategoryId, string Fallback)[] CategoryLabels =
    [
        ("medical", "Medical"),
        ("drug", "Drugs"),
        ("food", "Food"),
        ("water", "Drinks"),
        ("tool", "Tools"),
        ("utility", "Utility"),
        ("container", "Containers"),
        ("trash", "Trash"),
        ("custom", "Miscellaneous"),
        ("unobtainable", "Unobtainable"),
    ];

    public static string ModuleTitle(string langCode, string suffix)
    {
        return $"Module:Locale/{langCode}/{suffix}";
    }

    public static string BuildItemsModule(GameLocale locale, IReadOnlyCollection<string> itemIds)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var id in itemIds.OrderBy(x => x, StringComparer.Ordinal))
        {
            var name = locale.GetItemName(id);
            var description = locale.GetItemDescription(id);

            sb.Append("  [").Append(LuaFormat.String(id)).Append("] = { ");
            sb.Append("name = ").Append(LuaFormat.String(name)).Append(", ");
            sb.Append("description = ").Append(LuaFormat.String(description));
            sb.AppendLine(" },");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string BuildUiModule(GameLocale locale)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("return {");

        foreach (var (key, gameKey, fallback) in UiKeys)
        {
            var value = locale.GetOther(gameKey, fallback);
            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        foreach (var (categoryId, fallback) in CategoryLabels)
        {
            var key = "cat_" + categoryId;
            // Game locale has no dedicated category names; use English defaults until translators add keys.
            var value = locale.GetOther(key, fallback);
            sb.Append("  ").Append(key).Append(" = ").Append(LuaFormat.String(value)).AppendLine(",");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
